name: basalt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - py-opencv
  - cudatoolkit=10.0
  - pip:
    - crowdai_api
    - minerl
    - coloredlogs
    - matplotlib
    - pyro4
    - git+git://github.com/HumanCompatibleAI/imitation@master#egg=imitation
    - basalt_utils/
